# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

updateVoptimC <- function(XU, lambda, pvec, V) {
    invisible(.Call(`_SLIDE_updateVoptimC`, XU, lambda, pvec, V))
}

evaluatef_optimC <- function(XU, V, lambda, pvec) {
    .Call(`_SLIDE_evaluatef_optimC`, XU, V, lambda, pvec)
}

solve_optimC <- function(X, U, lambda, pvec, k_max = 1000L, eps = 1e-06) {
    .Call(`_SLIDE_solve_optimC`, X, U, lambda, pvec, k_max, eps)
}

solve_optim_seqC <- function(X, pvec, lambda_seq, k_max = 1000L, eps = 1e-06) {
    .Call(`_SLIDE_solve_optim_seqC`, X, pvec, lambda_seq, k_max, eps)
}

slide_givenS_C <- function(X, pvec, S, U, eps = 1e-06, k_max = 1000L) {
    .Call(`_SLIDE_slide_givenS_C`, X, pvec, S, U, eps, k_max)
}

rcpparma_hello_world <- function() {
    .Call(`_SLIDE_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_SLIDE_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_SLIDE_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_SLIDE_rcpparma_bothproducts`, x)
}

